name = colored_chests
depends = 
optional_depends = default, dye, mcl_formspec, mcl_sounds, doc, screwdriver, mcl_chests
author = SkyBuilder1717
description = Adds a colored chests!
title = Colored Chests
